server:
  port: 8082
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    format_sql: true
    show_sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect